--------------------------------------------------------------------------------
-- api.authorize_local ---------------------------------------------------------
--------------------------------------------------------------------------------
/**
 * @brief api.authorize for a pooled connection: the session context lives
 *        ONLY until the end of the current transaction.
 *
 * The platform's session context is nine `current.*` GUCs written with
 * set_config(…, false) — session-scoped, they survive COMMIT and are reset only
 * by the next SessionIn (skill, "Context and session"). That is right for the
 * C++ workers, which own a connection per request, and wrong for a Go module
 * behind pgx / pgbouncer in transaction mode: the next transaction on the same
 * backend would inherit the previous caller's identity. track-a-graftio.md §4
 * asks for SessionIn(pLocal); until SessionIn carries that parameter this
 * wrapper gives the same guarantee from the outside: it authorises through
 * Authorize, then moves every context GUC it set from the session level to the
 * transaction level — session value cleared to '' (GetVar reads '' as NULL),
 * the value re-set with is_local = true. After COMMIT or ROLLBACK the backend
 * carries no identity. The pool's RESET ALL on return is the second layer, not
 * the first.
 *
 * Contract К7: `sub` of the JWT is the session code; agent = User-Agent,
 * host = X-Forwarded-For. authorized = false → 401 with `message`.
 *
 * @param {varchar} pSession - Session code (JWT sub)
 * @param {text} pAgent - User-Agent
 * @param {inet} pHost - Client address
 * @return {record} authorized, userid, message — same shape as api.authorize
 * @since 1.2.21
 */
CREATE OR REPLACE FUNCTION api.authorize_local (
  pSession          varchar,
  pAgent            text DEFAULT null,
  pHost             inet DEFAULT null,
  OUT authorized    boolean,
  OUT userid        uuid,
  OUT message       text
) RETURNS           record
AS $$
DECLARE
  vName             text;
  vValue            text;
BEGIN
  authorized := Authorize(pSession, pAgent, pHost);
  userid := current_userid();
  message := GetErrorMessage();

  FOREACH vName IN ARRAY ARRAY['session', 'user', 'client_id', 'access', 'notification', 'area', 'oper_date', 'debug', 'log']
  LOOP
    vValue := current_setting('current.' || vName, true);
    IF vValue IS NOT NULL THEN
      PERFORM set_config('current.' || vName, '', false);
      PERFORM set_config('current.' || vName, vValue, true);
    END IF;
  END LOOP;
END;
$$ LANGUAGE plpgsql
   SECURITY DEFINER
   SET search_path = kernel, pg_temp;

GRANT EXECUTE ON FUNCTION api.authorize_local(varchar, text, inet) TO apibot;

--------------------------------------------------------------------------------
-- api.log_request -------------------------------------------------------------
--------------------------------------------------------------------------------
/**
 * @brief Journals one /api/v2 request into db.api_log the way api.run journals
 *        /api/v1 (track-a-graftio.md §4): AddApiLog — which a configuration may
 *        override with its own redaction list — plus the server-side runtime and
 *        the HTTP status, so a v2 line reads like a v1 line in the same table.
 *
 *        Call it at the END of the request, inside the same transaction as the
 *        work (the identity comes from the transaction-local context set by
 *        api.authorize_local): pRuntime is what the module measured, pStatus
 *        what it is about to answer. The request id (contract К7,
 *        X-Request-Id) and the method travel in `json` under "_request", next
 *        to the payload, because db.api_log has no column for either and a
 *        column is a platform change.
 *
 *        A refusal is a line too (1.2.24, go-platform T185): the module rolls
 *        the work back to a savepoint and calls this in the same transaction,
 *        or — when the refusal aborted the transaction before any savepoint —
 *        in a fresh one, with no session context at all. Nothing here needs a
 *        session: AddApiLog leaves `session` and `username` empty when
 *        current_session() names none. pError carries the catalogue code of
 *        the refusal (ERR-400-001, …) under "_request.error", so that a 4xx
 *        line says what was refused, not only that it was.
 *
 * @param {text} pMethod - HTTP method
 * @param {text} pPath - Request path as received (/api/v2/…)
 * @param {jsonb} pPayload - Request body (or query as an object); redacted by AddApiLog
 * @param {integer} pStatus - HTTP status the module answers with
 * @param {interval} pRuntime - Server-side duration measured by the module
 * @param {uuid} pRequestId - X-Request-Id generated by the gateway
 * @param {text} pError - Catalogue code of the error answered (NULL on success)
 * @return {bigint} db.api_log.id
 * @since 1.2.21
 */
CREATE OR REPLACE FUNCTION api.log_request (
  pMethod       text,
  pPath         text,
  pPayload      jsonb DEFAULT null,
  pStatus       integer DEFAULT null,
  pRuntime      interval DEFAULT null,
  pRequestId    uuid DEFAULT null,
  pError        text DEFAULT null
) RETURNS       bigint
AS $$
DECLARE
  nId           bigint;
BEGIN
  nId := AddApiLog(pPath, coalesce(pPayload, '{}'::jsonb)
                          || jsonb_build_object('_request', jsonb_strip_nulls(jsonb_build_object(
                               'method', pMethod, 'status', pStatus, 'id', pRequestId, 'error', pError))));

  IF pRuntime IS NOT NULL THEN
    UPDATE db.api_log SET runtime = pRuntime WHERE id = nId;
  END IF;

  RETURN nId;
END;
$$ LANGUAGE plpgsql
   SECURITY DEFINER
   SET search_path = kernel, pg_temp;

GRANT EXECUTE ON FUNCTION api.log_request(text, text, jsonb, integer, interval, uuid, text) TO apibot;

--------------------------------------------------------------------------------
-- api.parse_message -----------------------------------------------------------
--------------------------------------------------------------------------------
/**
 * @brief ParseMessage for the helper-pool role. track-a-graftio.md §4 asks for
 *        EXECUTE on kernel.ParseMessage for apibot; that grant would be dead —
 *        apibot has no USAGE on schema kernel, so the function is reached
 *        through api.*, like everything else the
 *        background roles call. Same OUT columns: code (ERR-GGG-CCC → HTTP-ish
 *        group), message, error (the code text) — what problem+json needs
 *        (contract К7: type = urn:apostol:error:<code>, status from GGG).
 *
 * @param {text} pMessage - SQLERRM as raised ("ERR-400-032: …")
 * @return {record} code, message, error
 * @since 1.2.21
 */
CREATE OR REPLACE FUNCTION api.parse_message (
  pMessage      text,
  OUT code      int,
  OUT message   text,
  OUT error     text
) RETURNS       record
AS $$
BEGIN
  SELECT p.code, p.message, p.error INTO code, message, error FROM ParseMessage(pMessage) p;
END;
$$ LANGUAGE plpgsql
   SECURITY DEFINER
   SET search_path = kernel, pg_temp;

GRANT EXECUTE ON FUNCTION api.parse_message(text) TO apibot;
