\echo [M] call db.sql
\ir db.sql

\echo [M] call api.sql
\ir api.sql

\echo [M] call rest.sql
\ir rest.sql

\echo [M] call event.sql
\ir event.sql

\echo [M] call init.sql
\ir init.sql

\ir './agent/install.psql'
\ir './calendar/install.psql'
\ir './category/install.psql'
\ir './model/install.psql'
\ir './program/install.psql'
\ir './scheduler/install.psql'
\ir './vendor/install.psql'
\ir './version/install.psql'
