DROP SCHEMA IF EXISTS rest CASCADE;
DROP SCHEMA IF EXISTS api CASCADE;

CREATE SCHEMA api AUTHORIZATION kernel;
CREATE SCHEMA rest AUTHORIZATION kernel;

GRANT USAGE ON SCHEMA api TO administrator;
GRANT USAGE ON SCHEMA rest TO administrator;
GRANT USAGE ON SCHEMA api TO apibot;
GRANT USAGE ON SCHEMA rest TO apibot;
