DROP VIEW ObjectAgent CASCADE;
DROP VIEW Agent CASCADE;

DROP VIEW ObjectForm CASCADE;
DROP VIEW Form CASCADE;

DROP VIEW ObjectProgram CASCADE;
DROP VIEW Program CASCADE;

DROP VIEW ObjectScheduler CASCADE;
DROP VIEW Scheduler CASCADE;

DROP VIEW ObjectVendor CASCADE;
DROP VIEW Vendor CASCADE;

DROP VIEW ObjectVersion CASCADE;
DROP VIEW Version CASCADE;

DROP VIEW ObjectJob CASCADE;
DROP VIEW Job CASCADE;

DROP VIEW ObjectMessage CASCADE;
DROP VIEW Message CASCADE;
